name: 'ledger_app'
version: '2.24'
services:
    nginx:
        container_name: 'ledger_app_nginx'
        build:
            context: .
            dockerfile: nginx.dockerfile
        ports:
            - 80:80
        # {hostPath}:{imagePath} volumes provide us the way to share data between host and container
        volumes:
            - ../:/var/www/html
        # This part for this container working depends on related containers, this container will wait the other containers to up.
        depends_on:
            - mysql
            - php
        networks:
            - ledger_app_network
    mysql:
        container_name: 'ledger_app_mysql'
        build:
            context: .
            dockerfile: mysql.dockerfile
        ports:
            - 3306:3306
        networks:
            - ledger_app_network
    php:
        container_name: 'ledger_app_php'
        build:
            context: .
            dockerfile: php.dockerfile
        volumes:
            - ../:/var/www/html
        networks:
            - ledger_app_network
    composer:
        container_name: 'ledger_app_composer'
        build:
            context: .
            dockerfile: composer.dockerfile
        volumes:
            - ../:/var/www/html
        networks:
            - ledger_app_network
    npm:
        container_name: 'ledger_app_npm'
        image: node:current-alpine
        volumes:
            - ../:/var/www/html
        entrypoint: [ 'npm' ]
        working_dir: /var/www/html
        networks:
            - ledger_app_network
    artisan:
        container_name: 'ledger_app_artisan'
        build:
            context: .
            dockerfile: php.dockerfile
        volumes:
            - ../:/var/www/html
        working_dir: /var/www/html
        depends_on:
            - mysql
        entrypoint: [ 'php', '/var/www/html/artisan' ]
        networks:
            - ledger_app_network
networks:
    ledger_app_network:
        driver: bridge
